apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-python-dibkagdc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/chetna14manku_org/backend-tests-python-dibkagdc:5cddbf9ce85518b34b51f5ab24b137e5d9a6ecad
        name: container-image  
